import { ProductType } from '../../enums/product-type.enum';
import { ProductStatus } from '../../enums/product-status.enum';

export interface CreateProduct {
  sku: string | null;
  name: string;
  description: string | null;
  productType: ProductType;
  status: ProductStatus;
  isActive: boolean;
  isTaxable: boolean;
  trackInventory: boolean;
  serialNumberTracking: boolean;
  batchTracking: boolean;
  itemGroupId: number | null;
  brandId: number | null;
  manufacturerPartNumber: string | null;
  upc: string | null;
  ean: string | null;
  isbn: string | null;
  sellingPrice: number | null;
  costPrice: number | null;
  salesAccountId: number | null;
  purchaseAccountId: number | null;
  inventoryAccountId: number | null;
  unitOfMeasureId: number | null;
  reorderLevel: number | null;
  reorderQuantity: number | null;
  minimumStock: number | null;
  maximumStock: number | null;
  openingStock: number | null;
  openingStockValue: number | null;
  isSaleable: boolean;
  isPurchasable: boolean;
  isReturnable: boolean;
  vendorId: number | null;
  weight: number | null;
  weightUnitId: number | null;
  length: number | null;
  width: number | null;
  height: number | null;
  dimensionUnitId: number | null;
  taxClassificationId: number | null;
  taxMasterId: number | null;
  isTaxExempt: boolean;
  taxExemptReason: string | null;
  tagIds: number[] | null;
  imageUrls: string[] | null;
}
